Repository thoth-station/reporter, pull requests merged in 2020-07, with the labels that each got.

#41 Automatic update of dependency thoth-common from 0.13.13 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/L

#42 Automatic update of dependency thoth-messaging from 0.3.6 to 0.3.7
  Pipfile.lock
Labels: approved, bot

#43 Automatic update of dependency thoth-messaging from 0.3.6 to 0.3.7
  Pipfile.lock
Labels: approved, bot, size/XS

#40 Migrate templates
  openshift/buildConfig-template.yaml
  openshift/consumer-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: size/L

#45 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/L

#44 Add pre commit
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  consumer.py
  producer.py
  thoth/advise_reporter/advise_reporter.py
Labels: approved, size/XL

#46 Expose metrics
  consumer.py
  thoth/advise_reporter/advise_reporter.py
  thoth/advise_reporter/metrics.py
Labels: approved, size/L

#48 Automatic update of dependency thoth-messaging from 0.3.7 to 0.5.0
  Pipfile.lock
Labels: approved, bot, size/M

#50 Use report processing
  Pipfile
  Pipfile.lock
  README.md
  app.sh
  consumer.py
  producer.py
  thoth/advise_reporter/__init__.py
  thoth/advise_reporter/advise_reporter.py
  thoth/advise_reporter/metrics.py
Labels: approved, size/XXL

#52 Automatic update of dependency hypothesis from 5.21.0 to 5.23.2
  Pipfile.lock
Labels: approved, bot, size/M

#54 Release of version 0.3.0
  CHANGELOG.md
  thoth/advise_reporter/__init__.py
Labels: approved, bot, size/S
