Repository thoth-station/reporter, pull requests merged in 2020-09, with the labels that each got.

#87 add component and version to message
  Pipfile.lock
  producer.py
Labels: approved, size/L

#89 Automatic update of dependency hypothesis from 5.32.0 to 5.33.1
  Pipfile.lock
Labels: approved, bot, size/L

#91 Release of version 0.3.3
  CHANGELOG.md
  thoth/advise_reporter/__init__.py
Labels: approved, bot, size/XS

#92 Act only as producer
  app.sh
  consumer.py
Labels: approved, size/M

#94 Automatic update of dependency thoth-report-processing from 0.3.0 to 0.3.4
  Pipfile.lock
Labels: approved, bot, size/L

#96 Automatic update of dependency thoth-common from 0.17.2 to 0.18.3
  Pipfile.lock
Labels: approved, bot

#98 Automatic update of dependency pytest from 6.0.1 to 6.0.2
  Pipfile.lock
Labels: approved, bot, size/L

#100 Automatic update of dependency hypothesis from 5.33.1 to 5.35.1
  Pipfile.lock
Labels: approved, bot, size/L

#101 Release of version 0.4.0
  CHANGELOG.md
  thoth/advise_reporter/__init__.py
Labels: approved, bot, size/S

#103 Correct variable name
  Pipfile.lock
  producer.py
Labels: approved, size/L

#105 Release of version 0.4.1
  CHANGELOG.md
  thoth/advise_reporter/__init__.py
Labels: approved, bot, size/XS

#106 Use correct variable
  producer.py
Labels: approved, size/XS

#108 Release of version 0.4.2
  CHANGELOG.md
  thoth/advise_reporter/__init__.py
Labels: approved, bot, size/XS

#109 Add missing parameter in message
  producer.py
Labels: approved, size/XS

#111 Release of version 0.4.3
  CHANGELOG.md
  thoth/advise_reporter/__init__.py
Labels: approved, bot, size/XS
