Repository thoth-station/reporter, pull requests merged in 2020-05, with the labels that each got.

#15 Adjust component
  .zuul.yaml
  advise_reporter.py
  app.sh
  consumer.py
  openshift/buildConfig-template.yaml
  openshift/consumer-template.yaml
  openshift/cronJob-template.yaml
  producer.py
Labels: approved, size/L

#18 Automatic update of dependency thoth-common from 0.13.2 to 0.13.6
  Pipfile.lock
Labels: bot, size/XL

#14 Automatic update of dependency thoth-messaging from 0.3.4 to 0.3.6
  Pipfile.lock
Labels: bot, size/XL

#20 Add env variable
  consumer.py
  openshift/consumer-template.yaml
  producer.py
  thoth/advise_reporter/__init__.py
  thoth/advise_reporter/advise_reporter.py
Labels: approved, size/M

#23 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/M

#24 Automatic update of dependency thoth-common from 0.13.7 to 0.13.8
  Pipfile.lock
Labels: bot, size/L
