Repository thoth-station/reporter, pull requests merged in 2020-10, with the labels that each got.

#113 Automatic update of dependency thoth-messaging from 0.7.6 to 0.7.10
  Pipfile.lock
Labels: approved, bot

#114 Automatic update of dependency pytest from 6.0.2 to 6.1.0
  Pipfile.lock
Labels: approved, bot

#115 Automatic update of dependency pytest from 6.0.2 to 6.1.0
  Pipfile.lock
Labels: approved, bot

#116 Automatic update of dependency hypothesis from 5.36.0 to 5.36.1
  Pipfile.lock
Labels: approved, bot, size/L

#119 Adjust logic and logging, refactor code and introduce day scheduling and filter for adviser version
  Pipfile
  Pipfile.lock
  producer.py
  thoth/advise_reporter/__init__.py
  thoth/advise_reporter/advise_reporter.py
  thoth/advise_reporter/metrics.py
Labels: approved, size/L

#122 Include all messages
  producer.py
  thoth/advise_reporter/advise_reporter.py
Labels: approved, size/M

#124 Use standard env variable only
  thoth/advise_reporter/advise_reporter.py
Labels: approved, size/XS

#130 Release of version 0.4.5
  CHANGELOG.md
  thoth/advise_reporter/__init__.py
Labels: approved, bot, size/XS

#128 Automatic update of dependency hypothesis from 5.37.0 to 5.37.1
  Pipfile.lock
Labels: approved, bot, size/L

#126 Automatic update of dependency thoth-common from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: approved, bot, size/L

#127 Automatic update of dependency thoth-messaging from 0.7.11 to 0.7.12
  Pipfile.lock
Labels: approved, bot, size/L

#133 lock down thoth-messaging
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#135 Automatic update of dependency thoth-common from 0.20.1 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/XL

#136 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/XL

#138 Automatic update of dependency hypothesis from 5.37.3 to 5.39.0
  Pipfile.lock
Labels: approved, bot, size/XL

#139 Release of version 0.4.6
  CHANGELOG.md
  thoth/advise_reporter/__init__.py
Labels: approved, bot, size/L
