Repository thoth-station/reporter, pull requests merged in 2020-08, with the labels that each got.

#58 Automatic update of dependency thoth-report-processing from 0.2.2 to 0.2.3
  Pipfile.lock
Labels: approved, bot, size/L

#61 Automatic update of dependency thoth-common from 0.14.2 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/L

#64 Automatic update of dependency pytest from 5.4.3 to 6.0.1
  Pipfile.lock
Labels: approved, bot, size/L

#69 Automatic update of dependency hypothesis from 5.23.2 to 5.23.12
  Pipfile.lock
Labels: approved, bot, size/L

#76 Correct typo for storage on Ceph
  thoth/advise_reporter/advise_reporter.py
Labels: approved, size/XS

#78 Automatic update of dependency thoth-report-processing from 0.2.3 to 0.2.4
  Pipfile.lock
Labels: approved, bot, size/XS

#79 Automatic update of dependency thoth-messaging from 0.6.2 to 0.6.3
  Pipfile.lock
Labels: approved, bot, size/XS

#80 Automatic update of dependency hypothesis from 5.23.12 to 5.24.0
  Pipfile.lock
Labels: approved, bot, size/XS

#77 Use only date to store
  thoth/advise_reporter/advise_reporter.py
Labels: approved, size/XS

#83 Release of version 0.3.1
  CHANGELOG.md
  thoth/advise_reporter/__init__.py
Labels: approved, bot, size/S

#84 Adjust filtering and storage
  thoth/advise_reporter/advise_reporter.py
Labels: approved, size/M

#86 Release of version 0.3.2
  CHANGELOG.md
  thoth/advise_reporter/__init__.py
Labels: approved, bot, size/XS
