Repository thoth-station/reporter, pull requests merged in 2021-01, with the labels that each got.

#146 Adjust processing of all justifications
  Pipfile.lock
  producer.py
  thoth/advise_reporter/advise_reporter.py
Labels: approved, size/XL

#151 update to latest messaging
  Pipfile
  Pipfile.lock
  app.sh
  producer.py
Labels: approved, do-not-merge/needs-rebase, size/L

#155 Change log to warning
  producer.py
Labels: approved, size/XS
