Repository thoth-station/reporter, pull requests merged in 2021-04, with the labels that each got.

#168 constrain thoth-messaging
  Pipfile
  Pipfile.lock
Labels: approved, size/XS

#179 Add analyzed data for adviser reports inputs and statistics
  .env.template
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  README.md
  docs/images/AdviserInputsAnalysis.jpg
  docs/images/AdviserQualityAnalysis.png
  producer.py
  thoth/advise_reporter/advise_reporter.py
  thoth/advise_reporter/processed_results.py
  thoth/advise_reporter/utils.py
Labels: approved, size/XL

#180 Adjust date inputs
  producer.py
Labels: approved, size/M

#183 fix loop exit
  producer.py
Labels: approved, size/S

#186 Remove unusued filter
  producer.py
  thoth/advise_reporter/processed_results.py
Labels: approved, size/S

#189 More logs
  producer.py
Labels: approved, size/M

#193 update schema and version
  Pipfile
  Pipfile.lock
  README.md
  docs/images/AdviserQualityAnalysis.jpg
  docs/images/AdviserQualityAnalysis.png
Labels: approved, size/M

#198 fix accidental use of contents instead of baseMessage instance
  .pre-commit-config.yaml
  .prow.yaml
  mypy.ini
  producer.py
Labels: approved, size/M

#200 Produce requests vs reports analysis
  .env.template
  OWNERS
  Pipfile.lock
  README.md
  producer.py
  thoth/reporter/__init__.py
  thoth/reporter/processing.py
  thoth/reporter/utils.py
Labels: approved, size/L
